cinema/cinema/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from films.views import index,add_film,rate_movie,signup, custom_logout,custom_login,film_detail
from django.contrib.auth.views import LogoutView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index, name='index'),
    path('upload/',add_film, name='upload'),
    path('signup/',signup,name='signup'),
    path('logout/',custom_logout, name='logout'),
    path('rate/<int:movie_id>/',rate_movie,name='rate_movie'),
    path('login/', custom_login, name='custom_login'),
    path('films/<int:film_id>/',film_detail,name='film_detail'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cinema/films/urls.py
from django.urls import path
from . import views
from .views import signup,rate_movie,custom_login,film_detail
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('', views.index, name='index'),
    path('upload/',views.add_film, name='upload'),
    path('signup/', views.signup, name='signup'),
    path('rate/<int:movie_id>/',views.rate_movie,name='rate_movie'),
    path( 'login/',custom_login, name='custom_login' ),
    path('films/<int:movie_id>/',name='film_detail'),

]

cinema/films/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.contrib.auth.models import AbstractUser


class Film(models.Model):
    title=models.CharField(max_length=100)
    description = models.CharField(max_length=10000)
    img = models.ImageField(upload_to='images',default='path/to/default/image.jpg')

    def __str__(self):
        return self.title


class CustomUser(AbstractUser):
    pass

    def __str__(self):
        return self.email


class Rating(models.Model):
    movie = models.ForeignKey(Film, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    value = models.IntegerField(default=0, validators=[MaxValueValidator(5), MinValueValidator(1)])

    class Meta:
        unique_together = ('movie', 'user')

cinema/films/forms.py
from django import forms
from .models import Film
from .models import Rating
from .models import CustomUser
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class FilmForm(forms.ModelForm):
    class Meta:
        model = Film
        fields = ('title', 'description', 'img')


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ('email', 'username',)


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ('email', 'username',)


class RatingForm(forms.ModelForm):
    class Meta:
        model = Rating
        fields = ['movie', 'value']

cinema/films/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import FilmForm, RatingForm, CustomUserCreationForm
from .models import Film, Rating
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.forms import AuthenticationForm


def index(request):
    movie = Film.objects.all()
    return render(request, 'index.html', {'movie': movie})


def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('/')
    else:
        form = CustomUserCreationForm()

    return render(request, 'signup.html', {'form': form})


def add_film(request):
    form = FilmForm()
    if request.method == 'POST':
        form = FilmForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('index')
        else:
            form = FilmForm()

    return render(request, 'film_upload.html', {'form': form})


def custom_logout(request):
    logout(request)
    return redirect('/')


def rate_movie(request, movie_id):
    movie = get_object_or_404(Film, id=movie_id)
    if request.method == 'POST':
        form = RatingForm(request.POST)
        if form.is_valid():
            rating = form.save(commit=False)
            rating.movie = movie
            rating.user = request.user
            rating.save()
            return redirect('index')
    else:
        form = RatingForm()

    return render(request, 'rate_movie.html', {'form': form, 'movie': movie})


def custom_login(request):
    if request.method == 'POST':
        login_form = AuthenticationForm(request, request.POST)
        if login_form.is_valid():
            username = login_form.cleaned_data['username']
            password = login_form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('/')
            else:
                error_message = "Неверный адрес электронной почты или пароль."
                return render(request, 'login.html', {'login_form': login_form, 'error_message': error_message})
    else:
        login_form = AuthenticationForm()
    return render(request, 'login.html', {'login_form': login_form})


def film_detail(request,film_id):
    film = get_object_or_404(Film, pk=film_id)
    return render(request,'film_detail.html',{'film':film})

cinema/films/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Кино{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
</head>
<body>
    <header>
        <div class="header-content">
            <h1>Кино</h1>
            <div class="user-info">
                {% if user.is_authenticated %}
                    <p>{{ user.username }}!</p>
                    <a href="{% url 'logout' %}">Выйти</a>
                {% else %}
                    <a href="{% url 'signup' %}">Зарегистрироваться</a>
                    <a href="{% url 'custom_login' %}">Войти</a>
                {% endif %}
            </div>
        </div>
    </header>
    <main>
        {% block content %}{% endblock %}
    </main>
</body>

    </main>
</body>
</html>

cinema/films/templates/film_detail.html
{% extends 'base.html' %}
{% block content %}
    <div class="film-details">
        <h2>{{ film.title }}</h2>
        <div class="film-poster">
            <img src="{{ film.img.url }}" alt="{{ film.title }} Poster">
        </div>
        <p>{{ film.description }}</p>
        {% with rating=film.rating_set.first %}
            {% if rating %}
                <p>Оценка: {{ rating.value }}/5</p>
            {% else %}
                <p>Оценка отсутствует</p>
            {% endif %}
        {% endwith %}
    </div>
{% endblock %}

cinema/films/templates/film_upload.html
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Добавить фильм</button>
</form>

cinema/films/templates/index.html
{% extends 'base.html' %}
{% block content %}
    <h2>Фильмы</h2>
    <ul>
        {% for film in movie %}
            <li>
                <div class="film-poster">
                    <img src="{{ film.img.url }}" alt="{{ film.title }} Poster">
                </div>
                <div class="film-details">
                    <h3><a href="{% url 'film_detail' film.id %}">{{ film.title }}</a></h3>
                    <p>{{ film.description }}</p>
                    {% with rating=film.rating_set.first %}
                        {% if rating %}
                            <p>Оценка: {{ rating.value }}/5</p>
                        {% else %}
                            <p>Оценка отсутствует</p>
                        {% endif %}
                    {% endwith %}
                </div>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

cinema/films/templates/login.html
{% extends 'base.html' %}

{% block content %}
    {% load static %}
    <h2>Login</h2>
    <form method="post" action="{% url 'custom_login' %}">
        {% csrf_token %}
        {{ login_form.username.label_tag }}
        {{ login_form.username }}
        {{ login_form.password.label_tag }}
        {{ login_form.password }}
        <button type="submit">Login</button>
    </form>
{% endblock %}

cinema/films/templates/rate_movie.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rate Movie</title>
</head>
<body>

  <h2>Rate Movie: {{ movie.title }}</h2>

  <form method="post" action="{% url 'rate_movie' movie_id=movie.id %}">
    {% csrf_token %}

    {{ form.as_p }}

    <button type="submit">Rate</button>
  </form>

</body>
</html>

cinema/films/templates/signin.html
{% extends 'base.html' %}

{% block content %}
    <h2>Sign In</h2>
    <form method="post" action="{% url 'signin' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Sign In</button>
    </form>
{% endblock %}

cinema/films/templates/signup.html
{% extends 'base.html' %}

{% block content %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/signup.css' %}">
    <h2>Sign Up</h2>
    <form method="post" action="{% url 'signup' %}">
        {% csrf_token %}

        <!-- Поле username -->
        <label for="{{ form.username.id_for_label }}">Username:</label>
        {{ form.username }}

        <!-- Поле email -->
        <label for="{{ form.email.id_for_label }}">Email:</label>
        {{ form.email }}

        <!-- Поле password1 -->
        <label for="{{ form.password1.id_for_label }}">Password:</label>
        {{ form.password1 }}

        <!-- Поле password2 -->
        <label for="{{ form.password2.id_for_label }}">Confirm Password:</label>
        {{ form.password2 }}

        <!-- Кнопка отправки формы -->
        <button type="submit">Sign Up</button>
    </form>
{% endblock %}